/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DELL' at '13/7/19 3:57 PM' with Gradle 3.0
 *
 * @author DELL, @date 13/7/19 3:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
