/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DELL' at '10/8/19 12:15 PM' with Gradle 3.0
 *
 * @author DELL, @date 10/8/19 12:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
