/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DELL' at '11/7/19 3:38 PM' with Gradle 3.0
 *
 * @author DELL, @date 11/7/19 3:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
