/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DELL' at '20/7/19 5:32 PM' with Gradle 3.0
 *
 * @author DELL, @date 20/7/19 5:32 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
