/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DELL' at '24/11/19 7:49 PM' with Gradle 3.0
 *
 * @author DELL, @date 24/11/19 7:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
