/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DELL' at '12/10/19 12:39 PM' with Gradle 3.0
 *
 * @author DELL, @date 12/10/19 12:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
