/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'DELL' at '8/7/19 2:43 PM' with Gradle 3.0
 *
 * @author DELL, @date 8/7/19 2:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
